// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: asb/v1/broker.proto

package asbv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/haasonsaas/asb/proto/asb/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BrokerServiceName is the fully-qualified name of the BrokerService service.
	BrokerServiceName = "asb.v1.BrokerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BrokerServiceCreateSessionProcedure is the fully-qualified name of the BrokerService's
	// CreateSession RPC.
	BrokerServiceCreateSessionProcedure = "/asb.v1.BrokerService/CreateSession"
	// BrokerServiceRequestGrantProcedure is the fully-qualified name of the BrokerService's
	// RequestGrant RPC.
	BrokerServiceRequestGrantProcedure = "/asb.v1.BrokerService/RequestGrant"
	// BrokerServiceApproveGrantProcedure is the fully-qualified name of the BrokerService's
	// ApproveGrant RPC.
	BrokerServiceApproveGrantProcedure = "/asb.v1.BrokerService/ApproveGrant"
	// BrokerServiceDenyGrantProcedure is the fully-qualified name of the BrokerService's DenyGrant RPC.
	BrokerServiceDenyGrantProcedure = "/asb.v1.BrokerService/DenyGrant"
	// BrokerServiceRevokeGrantProcedure is the fully-qualified name of the BrokerService's RevokeGrant
	// RPC.
	BrokerServiceRevokeGrantProcedure = "/asb.v1.BrokerService/RevokeGrant"
	// BrokerServiceRevokeSessionProcedure is the fully-qualified name of the BrokerService's
	// RevokeSession RPC.
	BrokerServiceRevokeSessionProcedure = "/asb.v1.BrokerService/RevokeSession"
	// BrokerServiceExecuteGitHubProxyProcedure is the fully-qualified name of the BrokerService's
	// ExecuteGitHubProxy RPC.
	BrokerServiceExecuteGitHubProxyProcedure = "/asb.v1.BrokerService/ExecuteGitHubProxy"
	// BrokerServiceRegisterBrowserRelayProcedure is the fully-qualified name of the BrokerService's
	// RegisterBrowserRelay RPC.
	BrokerServiceRegisterBrowserRelayProcedure = "/asb.v1.BrokerService/RegisterBrowserRelay"
	// BrokerServiceUnwrapArtifactProcedure is the fully-qualified name of the BrokerService's
	// UnwrapArtifact RPC.
	BrokerServiceUnwrapArtifactProcedure = "/asb.v1.BrokerService/UnwrapArtifact"
)

// BrokerServiceClient is a client for the asb.v1.BrokerService service.
type BrokerServiceClient interface {
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	RequestGrant(context.Context, *connect.Request[v1.RequestGrantRequest]) (*connect.Response[v1.RequestGrantResponse], error)
	ApproveGrant(context.Context, *connect.Request[v1.ApproveGrantRequest]) (*connect.Response[v1.ApproveGrantResponse], error)
	DenyGrant(context.Context, *connect.Request[v1.DenyGrantRequest]) (*connect.Response[v1.DenyGrantResponse], error)
	RevokeGrant(context.Context, *connect.Request[v1.RevokeGrantRequest]) (*connect.Response[v1.RevokeGrantResponse], error)
	RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error)
	ExecuteGitHubProxy(context.Context, *connect.Request[v1.ExecuteGitHubProxyRequest]) (*connect.Response[v1.ExecuteGitHubProxyResponse], error)
	RegisterBrowserRelay(context.Context, *connect.Request[v1.RegisterBrowserRelayRequest]) (*connect.Response[v1.RegisterBrowserRelayResponse], error)
	UnwrapArtifact(context.Context, *connect.Request[v1.UnwrapArtifactRequest]) (*connect.Response[v1.UnwrapArtifactResponse], error)
}

// NewBrokerServiceClient constructs a client for the asb.v1.BrokerService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBrokerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BrokerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	brokerServiceMethods := v1.File_asb_v1_broker_proto.Services().ByName("BrokerService").Methods()
	return &brokerServiceClient{
		createSession: connect.NewClient[v1.CreateSessionRequest, v1.CreateSessionResponse](
			httpClient,
			baseURL+BrokerServiceCreateSessionProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		requestGrant: connect.NewClient[v1.RequestGrantRequest, v1.RequestGrantResponse](
			httpClient,
			baseURL+BrokerServiceRequestGrantProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("RequestGrant")),
			connect.WithClientOptions(opts...),
		),
		approveGrant: connect.NewClient[v1.ApproveGrantRequest, v1.ApproveGrantResponse](
			httpClient,
			baseURL+BrokerServiceApproveGrantProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("ApproveGrant")),
			connect.WithClientOptions(opts...),
		),
		denyGrant: connect.NewClient[v1.DenyGrantRequest, v1.DenyGrantResponse](
			httpClient,
			baseURL+BrokerServiceDenyGrantProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("DenyGrant")),
			connect.WithClientOptions(opts...),
		),
		revokeGrant: connect.NewClient[v1.RevokeGrantRequest, v1.RevokeGrantResponse](
			httpClient,
			baseURL+BrokerServiceRevokeGrantProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("RevokeGrant")),
			connect.WithClientOptions(opts...),
		),
		revokeSession: connect.NewClient[v1.RevokeSessionRequest, v1.RevokeSessionResponse](
			httpClient,
			baseURL+BrokerServiceRevokeSessionProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("RevokeSession")),
			connect.WithClientOptions(opts...),
		),
		executeGitHubProxy: connect.NewClient[v1.ExecuteGitHubProxyRequest, v1.ExecuteGitHubProxyResponse](
			httpClient,
			baseURL+BrokerServiceExecuteGitHubProxyProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("ExecuteGitHubProxy")),
			connect.WithClientOptions(opts...),
		),
		registerBrowserRelay: connect.NewClient[v1.RegisterBrowserRelayRequest, v1.RegisterBrowserRelayResponse](
			httpClient,
			baseURL+BrokerServiceRegisterBrowserRelayProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("RegisterBrowserRelay")),
			connect.WithClientOptions(opts...),
		),
		unwrapArtifact: connect.NewClient[v1.UnwrapArtifactRequest, v1.UnwrapArtifactResponse](
			httpClient,
			baseURL+BrokerServiceUnwrapArtifactProcedure,
			connect.WithSchema(brokerServiceMethods.ByName("UnwrapArtifact")),
			connect.WithClientOptions(opts...),
		),
	}
}

// brokerServiceClient implements BrokerServiceClient.
type brokerServiceClient struct {
	createSession        *connect.Client[v1.CreateSessionRequest, v1.CreateSessionResponse]
	requestGrant         *connect.Client[v1.RequestGrantRequest, v1.RequestGrantResponse]
	approveGrant         *connect.Client[v1.ApproveGrantRequest, v1.ApproveGrantResponse]
	denyGrant            *connect.Client[v1.DenyGrantRequest, v1.DenyGrantResponse]
	revokeGrant          *connect.Client[v1.RevokeGrantRequest, v1.RevokeGrantResponse]
	revokeSession        *connect.Client[v1.RevokeSessionRequest, v1.RevokeSessionResponse]
	executeGitHubProxy   *connect.Client[v1.ExecuteGitHubProxyRequest, v1.ExecuteGitHubProxyResponse]
	registerBrowserRelay *connect.Client[v1.RegisterBrowserRelayRequest, v1.RegisterBrowserRelayResponse]
	unwrapArtifact       *connect.Client[v1.UnwrapArtifactRequest, v1.UnwrapArtifactResponse]
}

// CreateSession calls asb.v1.BrokerService.CreateSession.
func (c *brokerServiceClient) CreateSession(ctx context.Context, req *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// RequestGrant calls asb.v1.BrokerService.RequestGrant.
func (c *brokerServiceClient) RequestGrant(ctx context.Context, req *connect.Request[v1.RequestGrantRequest]) (*connect.Response[v1.RequestGrantResponse], error) {
	return c.requestGrant.CallUnary(ctx, req)
}

// ApproveGrant calls asb.v1.BrokerService.ApproveGrant.
func (c *brokerServiceClient) ApproveGrant(ctx context.Context, req *connect.Request[v1.ApproveGrantRequest]) (*connect.Response[v1.ApproveGrantResponse], error) {
	return c.approveGrant.CallUnary(ctx, req)
}

// DenyGrant calls asb.v1.BrokerService.DenyGrant.
func (c *brokerServiceClient) DenyGrant(ctx context.Context, req *connect.Request[v1.DenyGrantRequest]) (*connect.Response[v1.DenyGrantResponse], error) {
	return c.denyGrant.CallUnary(ctx, req)
}

// RevokeGrant calls asb.v1.BrokerService.RevokeGrant.
func (c *brokerServiceClient) RevokeGrant(ctx context.Context, req *connect.Request[v1.RevokeGrantRequest]) (*connect.Response[v1.RevokeGrantResponse], error) {
	return c.revokeGrant.CallUnary(ctx, req)
}

// RevokeSession calls asb.v1.BrokerService.RevokeSession.
func (c *brokerServiceClient) RevokeSession(ctx context.Context, req *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error) {
	return c.revokeSession.CallUnary(ctx, req)
}

// ExecuteGitHubProxy calls asb.v1.BrokerService.ExecuteGitHubProxy.
func (c *brokerServiceClient) ExecuteGitHubProxy(ctx context.Context, req *connect.Request[v1.ExecuteGitHubProxyRequest]) (*connect.Response[v1.ExecuteGitHubProxyResponse], error) {
	return c.executeGitHubProxy.CallUnary(ctx, req)
}

// RegisterBrowserRelay calls asb.v1.BrokerService.RegisterBrowserRelay.
func (c *brokerServiceClient) RegisterBrowserRelay(ctx context.Context, req *connect.Request[v1.RegisterBrowserRelayRequest]) (*connect.Response[v1.RegisterBrowserRelayResponse], error) {
	return c.registerBrowserRelay.CallUnary(ctx, req)
}

// UnwrapArtifact calls asb.v1.BrokerService.UnwrapArtifact.
func (c *brokerServiceClient) UnwrapArtifact(ctx context.Context, req *connect.Request[v1.UnwrapArtifactRequest]) (*connect.Response[v1.UnwrapArtifactResponse], error) {
	return c.unwrapArtifact.CallUnary(ctx, req)
}

// BrokerServiceHandler is an implementation of the asb.v1.BrokerService service.
type BrokerServiceHandler interface {
	CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error)
	RequestGrant(context.Context, *connect.Request[v1.RequestGrantRequest]) (*connect.Response[v1.RequestGrantResponse], error)
	ApproveGrant(context.Context, *connect.Request[v1.ApproveGrantRequest]) (*connect.Response[v1.ApproveGrantResponse], error)
	DenyGrant(context.Context, *connect.Request[v1.DenyGrantRequest]) (*connect.Response[v1.DenyGrantResponse], error)
	RevokeGrant(context.Context, *connect.Request[v1.RevokeGrantRequest]) (*connect.Response[v1.RevokeGrantResponse], error)
	RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error)
	ExecuteGitHubProxy(context.Context, *connect.Request[v1.ExecuteGitHubProxyRequest]) (*connect.Response[v1.ExecuteGitHubProxyResponse], error)
	RegisterBrowserRelay(context.Context, *connect.Request[v1.RegisterBrowserRelayRequest]) (*connect.Response[v1.RegisterBrowserRelayResponse], error)
	UnwrapArtifact(context.Context, *connect.Request[v1.UnwrapArtifactRequest]) (*connect.Response[v1.UnwrapArtifactResponse], error)
}

// NewBrokerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBrokerServiceHandler(svc BrokerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	brokerServiceMethods := v1.File_asb_v1_broker_proto.Services().ByName("BrokerService").Methods()
	brokerServiceCreateSessionHandler := connect.NewUnaryHandler(
		BrokerServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(brokerServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceRequestGrantHandler := connect.NewUnaryHandler(
		BrokerServiceRequestGrantProcedure,
		svc.RequestGrant,
		connect.WithSchema(brokerServiceMethods.ByName("RequestGrant")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceApproveGrantHandler := connect.NewUnaryHandler(
		BrokerServiceApproveGrantProcedure,
		svc.ApproveGrant,
		connect.WithSchema(brokerServiceMethods.ByName("ApproveGrant")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceDenyGrantHandler := connect.NewUnaryHandler(
		BrokerServiceDenyGrantProcedure,
		svc.DenyGrant,
		connect.WithSchema(brokerServiceMethods.ByName("DenyGrant")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceRevokeGrantHandler := connect.NewUnaryHandler(
		BrokerServiceRevokeGrantProcedure,
		svc.RevokeGrant,
		connect.WithSchema(brokerServiceMethods.ByName("RevokeGrant")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceRevokeSessionHandler := connect.NewUnaryHandler(
		BrokerServiceRevokeSessionProcedure,
		svc.RevokeSession,
		connect.WithSchema(brokerServiceMethods.ByName("RevokeSession")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceExecuteGitHubProxyHandler := connect.NewUnaryHandler(
		BrokerServiceExecuteGitHubProxyProcedure,
		svc.ExecuteGitHubProxy,
		connect.WithSchema(brokerServiceMethods.ByName("ExecuteGitHubProxy")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceRegisterBrowserRelayHandler := connect.NewUnaryHandler(
		BrokerServiceRegisterBrowserRelayProcedure,
		svc.RegisterBrowserRelay,
		connect.WithSchema(brokerServiceMethods.ByName("RegisterBrowserRelay")),
		connect.WithHandlerOptions(opts...),
	)
	brokerServiceUnwrapArtifactHandler := connect.NewUnaryHandler(
		BrokerServiceUnwrapArtifactProcedure,
		svc.UnwrapArtifact,
		connect.WithSchema(brokerServiceMethods.ByName("UnwrapArtifact")),
		connect.WithHandlerOptions(opts...),
	)
	return "/asb.v1.BrokerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BrokerServiceCreateSessionProcedure:
			brokerServiceCreateSessionHandler.ServeHTTP(w, r)
		case BrokerServiceRequestGrantProcedure:
			brokerServiceRequestGrantHandler.ServeHTTP(w, r)
		case BrokerServiceApproveGrantProcedure:
			brokerServiceApproveGrantHandler.ServeHTTP(w, r)
		case BrokerServiceDenyGrantProcedure:
			brokerServiceDenyGrantHandler.ServeHTTP(w, r)
		case BrokerServiceRevokeGrantProcedure:
			brokerServiceRevokeGrantHandler.ServeHTTP(w, r)
		case BrokerServiceRevokeSessionProcedure:
			brokerServiceRevokeSessionHandler.ServeHTTP(w, r)
		case BrokerServiceExecuteGitHubProxyProcedure:
			brokerServiceExecuteGitHubProxyHandler.ServeHTTP(w, r)
		case BrokerServiceRegisterBrowserRelayProcedure:
			brokerServiceRegisterBrowserRelayHandler.ServeHTTP(w, r)
		case BrokerServiceUnwrapArtifactProcedure:
			brokerServiceUnwrapArtifactHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBrokerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBrokerServiceHandler struct{}

func (UnimplementedBrokerServiceHandler) CreateSession(context.Context, *connect.Request[v1.CreateSessionRequest]) (*connect.Response[v1.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.CreateSession is not implemented"))
}

func (UnimplementedBrokerServiceHandler) RequestGrant(context.Context, *connect.Request[v1.RequestGrantRequest]) (*connect.Response[v1.RequestGrantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.RequestGrant is not implemented"))
}

func (UnimplementedBrokerServiceHandler) ApproveGrant(context.Context, *connect.Request[v1.ApproveGrantRequest]) (*connect.Response[v1.ApproveGrantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.ApproveGrant is not implemented"))
}

func (UnimplementedBrokerServiceHandler) DenyGrant(context.Context, *connect.Request[v1.DenyGrantRequest]) (*connect.Response[v1.DenyGrantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.DenyGrant is not implemented"))
}

func (UnimplementedBrokerServiceHandler) RevokeGrant(context.Context, *connect.Request[v1.RevokeGrantRequest]) (*connect.Response[v1.RevokeGrantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.RevokeGrant is not implemented"))
}

func (UnimplementedBrokerServiceHandler) RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.RevokeSession is not implemented"))
}

func (UnimplementedBrokerServiceHandler) ExecuteGitHubProxy(context.Context, *connect.Request[v1.ExecuteGitHubProxyRequest]) (*connect.Response[v1.ExecuteGitHubProxyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.ExecuteGitHubProxy is not implemented"))
}

func (UnimplementedBrokerServiceHandler) RegisterBrowserRelay(context.Context, *connect.Request[v1.RegisterBrowserRelayRequest]) (*connect.Response[v1.RegisterBrowserRelayResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.RegisterBrowserRelay is not implemented"))
}

func (UnimplementedBrokerServiceHandler) UnwrapArtifact(context.Context, *connect.Request[v1.UnwrapArtifactRequest]) (*connect.Response[v1.UnwrapArtifactResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("asb.v1.BrokerService.UnwrapArtifact is not implemented"))
}
