// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: asb/v1/broker.proto

package asbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attestation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_asb_v1_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{0}
}

func (x *Attestation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Attestation) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Delivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Handle        string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,4,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_asb_v1_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{1}
}

func (x *Delivery) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Delivery) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Delivery) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Delivery) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type BrowserFillField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserFillField) Reset() {
	*x = BrowserFillField{}
	mi := &file_asb_v1_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserFillField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserFillField) ProtoMessage() {}

func (x *BrowserFillField) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserFillField.ProtoReflect.Descriptor instead.
func (*BrowserFillField) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{2}
}

func (x *BrowserFillField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrowserFillField) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *BrowserFillField) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CreateSessionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TenantId            string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AgentId             string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	RunId               string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ToolContext         []string               `protobuf:"bytes,4,rep,name=tool_context,json=toolContext,proto3" json:"tool_context,omitempty"`
	Attestation         *Attestation           `protobuf:"bytes,5,opt,name=attestation,proto3" json:"attestation,omitempty"`
	DelegationAssertion string                 `protobuf:"bytes,6,opt,name=delegation_assertion,json=delegationAssertion,proto3" json:"delegation_assertion,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateSessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateSessionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *CreateSessionRequest) GetToolContext() []string {
	if x != nil {
		return x.ToolContext
	}
	return nil
}

func (x *CreateSessionRequest) GetAttestation() *Attestation {
	if x != nil {
		return x.Attestation
	}
	return nil
}

func (x *CreateSessionRequest) GetDelegationAssertion() string {
	if x != nil {
		return x.DelegationAssertion
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionToken  string                 `protobuf:"bytes,2,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *CreateSessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RequestGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Capability    string                 `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	ResourceRef   string                 `protobuf:"bytes,4,opt,name=resource_ref,json=resourceRef,proto3" json:"resource_ref,omitempty"`
	DeliveryMode  string                 `protobuf:"bytes,5,opt,name=delivery_mode,json=deliveryMode,proto3" json:"delivery_mode,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Reason        string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGrantRequest) Reset() {
	*x = RequestGrantRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGrantRequest) ProtoMessage() {}

func (x *RequestGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGrantRequest.ProtoReflect.Descriptor instead.
func (*RequestGrantRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{5}
}

func (x *RequestGrantRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RequestGrantRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *RequestGrantRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *RequestGrantRequest) GetResourceRef() string {
	if x != nil {
		return x.ResourceRef
	}
	return ""
}

func (x *RequestGrantRequest) GetDeliveryMode() string {
	if x != nil {
		return x.DeliveryMode
	}
	return ""
}

func (x *RequestGrantRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *RequestGrantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RequestGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ApprovalId    string                 `protobuf:"bytes,3,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	Delivery      *Delivery              `protobuf:"bytes,4,opt,name=delivery,proto3" json:"delivery,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGrantResponse) Reset() {
	*x = RequestGrantResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGrantResponse) ProtoMessage() {}

func (x *RequestGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGrantResponse.ProtoReflect.Descriptor instead.
func (*RequestGrantResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{6}
}

func (x *RequestGrantResponse) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *RequestGrantResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RequestGrantResponse) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *RequestGrantResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *RequestGrantResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ApproveGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	Approver      string                 `protobuf:"bytes,2,opt,name=approver,proto3" json:"approver,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveGrantRequest) Reset() {
	*x = ApproveGrantRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveGrantRequest) ProtoMessage() {}

func (x *ApproveGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveGrantRequest.ProtoReflect.Descriptor instead.
func (*ApproveGrantRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{7}
}

func (x *ApproveGrantRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApproveGrantRequest) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *ApproveGrantRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type ApproveGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	ApprovalId    string                 `protobuf:"bytes,3,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	Delivery      *Delivery              `protobuf:"bytes,4,opt,name=delivery,proto3" json:"delivery,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveGrantResponse) Reset() {
	*x = ApproveGrantResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveGrantResponse) ProtoMessage() {}

func (x *ApproveGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveGrantResponse.ProtoReflect.Descriptor instead.
func (*ApproveGrantResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{8}
}

func (x *ApproveGrantResponse) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *ApproveGrantResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ApproveGrantResponse) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *ApproveGrantResponse) GetDelivery() *Delivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *ApproveGrantResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type DenyGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApprovalId    string                 `protobuf:"bytes,1,opt,name=approval_id,json=approvalId,proto3" json:"approval_id,omitempty"`
	Approver      string                 `protobuf:"bytes,2,opt,name=approver,proto3" json:"approver,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyGrantRequest) Reset() {
	*x = DenyGrantRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyGrantRequest) ProtoMessage() {}

func (x *DenyGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyGrantRequest.ProtoReflect.Descriptor instead.
func (*DenyGrantRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{9}
}

func (x *DenyGrantRequest) GetApprovalId() string {
	if x != nil {
		return x.ApprovalId
	}
	return ""
}

func (x *DenyGrantRequest) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *DenyGrantRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type DenyGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DenyGrantResponse) Reset() {
	*x = DenyGrantResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DenyGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DenyGrantResponse) ProtoMessage() {}

func (x *DenyGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DenyGrantResponse.ProtoReflect.Descriptor instead.
func (*DenyGrantResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{10}
}

func (x *DenyGrantResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type RevokeGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeGrantRequest) Reset() {
	*x = RevokeGrantRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeGrantRequest) ProtoMessage() {}

func (x *RevokeGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeGrantRequest.ProtoReflect.Descriptor instead.
func (*RevokeGrantRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeGrantRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *RevokeGrantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeGrantResponse) Reset() {
	*x = RevokeGrantResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeGrantResponse) ProtoMessage() {}

func (x *RevokeGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeGrantResponse.ProtoReflect.Descriptor instead.
func (*RevokeGrantResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeGrantResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RevokeSessionRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeSessionResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ExecuteGitHubProxyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyHandle   string                 `protobuf:"bytes,1,opt,name=proxy_handle,json=proxyHandle,proto3" json:"proxy_handle,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteGitHubProxyRequest) Reset() {
	*x = ExecuteGitHubProxyRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteGitHubProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteGitHubProxyRequest) ProtoMessage() {}

func (x *ExecuteGitHubProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteGitHubProxyRequest.ProtoReflect.Descriptor instead.
func (*ExecuteGitHubProxyRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteGitHubProxyRequest) GetProxyHandle() string {
	if x != nil {
		return x.ProxyHandle
	}
	return ""
}

func (x *ExecuteGitHubProxyRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ExecuteGitHubProxyRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteGitHubProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteGitHubProxyResponse) Reset() {
	*x = ExecuteGitHubProxyResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteGitHubProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteGitHubProxyResponse) ProtoMessage() {}

func (x *ExecuteGitHubProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteGitHubProxyResponse.ProtoReflect.Descriptor instead.
func (*ExecuteGitHubProxyResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteGitHubProxyResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteGitHubProxyResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type RegisterBrowserRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Origin        string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	TabId         string                 `protobuf:"bytes,5,opt,name=tab_id,json=tabId,proto3" json:"tab_id,omitempty"`
	Selectors     map[string]string      `protobuf:"bytes,6,rep,name=selectors,proto3" json:"selectors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBrowserRelayRequest) Reset() {
	*x = RegisterBrowserRelayRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBrowserRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrowserRelayRequest) ProtoMessage() {}

func (x *RegisterBrowserRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrowserRelayRequest.ProtoReflect.Descriptor instead.
func (*RegisterBrowserRelayRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterBrowserRelayRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterBrowserRelayRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RegisterBrowserRelayRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegisterBrowserRelayRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *RegisterBrowserRelayRequest) GetTabId() string {
	if x != nil {
		return x.TabId
	}
	return ""
}

func (x *RegisterBrowserRelayRequest) GetSelectors() map[string]string {
	if x != nil {
		return x.Selectors
	}
	return nil
}

type RegisterBrowserRelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBrowserRelayResponse) Reset() {
	*x = RegisterBrowserRelayResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBrowserRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBrowserRelayResponse) ProtoMessage() {}

func (x *RegisterBrowserRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBrowserRelayResponse.ProtoReflect.Descriptor instead.
func (*RegisterBrowserRelayResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterBrowserRelayResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterBrowserRelayResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *RegisterBrowserRelayResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type UnwrapArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,3,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Origin        string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	TabId         string                 `protobuf:"bytes,5,opt,name=tab_id,json=tabId,proto3" json:"tab_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapArtifactRequest) Reset() {
	*x = UnwrapArtifactRequest{}
	mi := &file_asb_v1_broker_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapArtifactRequest) ProtoMessage() {}

func (x *UnwrapArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapArtifactRequest.ProtoReflect.Descriptor instead.
func (*UnwrapArtifactRequest) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{19}
}

func (x *UnwrapArtifactRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *UnwrapArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *UnwrapArtifactRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *UnwrapArtifactRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *UnwrapArtifactRequest) GetTabId() string {
	if x != nil {
		return x.TabId
	}
	return ""
}

type UnwrapArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	AutoSubmit    bool                   `protobuf:"varint,3,opt,name=auto_submit,json=autoSubmit,proto3" json:"auto_submit,omitempty"`
	Fields        []*BrowserFillField    `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnwrapArtifactResponse) Reset() {
	*x = UnwrapArtifactResponse{}
	mi := &file_asb_v1_broker_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnwrapArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnwrapArtifactResponse) ProtoMessage() {}

func (x *UnwrapArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asb_v1_broker_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnwrapArtifactResponse.ProtoReflect.Descriptor instead.
func (*UnwrapArtifactResponse) Descriptor() ([]byte, []int) {
	return file_asb_v1_broker_proto_rawDescGZIP(), []int{20}
}

func (x *UnwrapArtifactResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *UnwrapArtifactResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *UnwrapArtifactResponse) GetAutoSubmit() bool {
	if x != nil {
		return x.AutoSubmit
	}
	return false
}

func (x *UnwrapArtifactResponse) GetFields() []*BrowserFillField {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_asb_v1_broker_proto protoreflect.FileDescriptor

const file_asb_v1_broker_proto_rawDesc = "" +
	"\n" +
	"\x13asb/v1/broker.proto\x12\x06asb.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\vAttestation\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"m\n" +
	"\bDelivery\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1f\n" +
	"\vartifact_id\x18\x04 \x01(\tR\n" +
	"artifactId\"X\n" +
	"\x10BrowserFillField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\xf2\x01\n" +
	"\x14CreateSessionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12!\n" +
	"\ftool_context\x18\x04 \x03(\tR\vtoolContext\x125\n" +
	"\vattestation\x18\x05 \x01(\v2\x13.asb.v1.AttestationR\vattestation\x121\n" +
	"\x14delegation_assertion\x18\x06 \x01(\tR\x13delegationAssertion\"\x96\x01\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rsession_token\x18\x02 \x01(\tR\fsessionToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xef\x01\n" +
	"\x13RequestGrantRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\tR\n" +
	"capability\x12!\n" +
	"\fresource_ref\x18\x04 \x01(\tR\vresourceRef\x12#\n" +
	"\rdelivery_mode\x18\x05 \x01(\tR\fdeliveryMode\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\x03R\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\"\xd1\x01\n" +
	"\x14RequestGrantResponse\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vapproval_id\x18\x03 \x01(\tR\n" +
	"approvalId\x12,\n" +
	"\bdelivery\x18\x04 \x01(\v2\x10.asb.v1.DeliveryR\bdelivery\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"l\n" +
	"\x13ApproveGrantRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1a\n" +
	"\bapprover\x18\x02 \x01(\tR\bapprover\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"\xd1\x01\n" +
	"\x14ApproveGrantResponse\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x1f\n" +
	"\vapproval_id\x18\x03 \x01(\tR\n" +
	"approvalId\x12,\n" +
	"\bdelivery\x18\x04 \x01(\v2\x10.asb.v1.DeliveryR\bdelivery\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"i\n" +
	"\x10DenyGrantRequest\x12\x1f\n" +
	"\vapproval_id\x18\x01 \x01(\tR\n" +
	"approvalId\x12\x1a\n" +
	"\bapprover\x18\x02 \x01(\tR\bapprover\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\")\n" +
	"\x11DenyGrantResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"G\n" +
	"\x12RevokeGrantRequest\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"+\n" +
	"\x13RevokeGrantResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"M\n" +
	"\x14RevokeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"-\n" +
	"\x15RevokeSessionResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\"\x8d\x01\n" +
	"\x19ExecuteGitHubProxyRequest\x12!\n" +
	"\fproxy_handle\x18\x01 \x01(\tR\vproxyHandle\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\"Y\n" +
	"\x1aExecuteGitHubProxyResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"\xb7\x02\n" +
	"\x1bRegisterBrowserRelayRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12\x15\n" +
	"\x06tab_id\x18\x05 \x01(\tR\x05tabId\x12P\n" +
	"\tselectors\x18\x06 \x03(\v22.asb.v1.RegisterBrowserRelayRequest.SelectorsEntryR\tselectors\x1a<\n" +
	"\x0eSelectorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x1cRegisterBrowserRelayResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa3\x01\n" +
	"\x15UnwrapArtifactRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x15\n" +
	"\x06key_id\x18\x03 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12\x15\n" +
	"\x06tab_id\x18\x05 \x01(\tR\x05tabId\"\xa4\x01\n" +
	"\x16UnwrapArtifactResponse\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\x12\x1f\n" +
	"\vauto_submit\x18\x03 \x01(\bR\n" +
	"autoSubmit\x120\n" +
	"\x06fields\x18\x04 \x03(\v2\x18.asb.v1.BrowserFillFieldR\x06fields2\xdc\x05\n" +
	"\rBrokerService\x12L\n" +
	"\rCreateSession\x12\x1c.asb.v1.CreateSessionRequest\x1a\x1d.asb.v1.CreateSessionResponse\x12I\n" +
	"\fRequestGrant\x12\x1b.asb.v1.RequestGrantRequest\x1a\x1c.asb.v1.RequestGrantResponse\x12I\n" +
	"\fApproveGrant\x12\x1b.asb.v1.ApproveGrantRequest\x1a\x1c.asb.v1.ApproveGrantResponse\x12@\n" +
	"\tDenyGrant\x12\x18.asb.v1.DenyGrantRequest\x1a\x19.asb.v1.DenyGrantResponse\x12F\n" +
	"\vRevokeGrant\x12\x1a.asb.v1.RevokeGrantRequest\x1a\x1b.asb.v1.RevokeGrantResponse\x12L\n" +
	"\rRevokeSession\x12\x1c.asb.v1.RevokeSessionRequest\x1a\x1d.asb.v1.RevokeSessionResponse\x12[\n" +
	"\x12ExecuteGitHubProxy\x12!.asb.v1.ExecuteGitHubProxyRequest\x1a\".asb.v1.ExecuteGitHubProxyResponse\x12a\n" +
	"\x14RegisterBrowserRelay\x12#.asb.v1.RegisterBrowserRelayRequest\x1a$.asb.v1.RegisterBrowserRelayResponse\x12O\n" +
	"\x0eUnwrapArtifact\x12\x1d.asb.v1.UnwrapArtifactRequest\x1a\x1e.asb.v1.UnwrapArtifactResponseB.Z,github.com/haasonsaas/asb/proto/asb/v1;asbv1b\x06proto3"

var (
	file_asb_v1_broker_proto_rawDescOnce sync.Once
	file_asb_v1_broker_proto_rawDescData []byte
)

func file_asb_v1_broker_proto_rawDescGZIP() []byte {
	file_asb_v1_broker_proto_rawDescOnce.Do(func() {
		file_asb_v1_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asb_v1_broker_proto_rawDesc), len(file_asb_v1_broker_proto_rawDesc)))
	})
	return file_asb_v1_broker_proto_rawDescData
}

var file_asb_v1_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_asb_v1_broker_proto_goTypes = []any{
	(*Attestation)(nil),                  // 0: asb.v1.Attestation
	(*Delivery)(nil),                     // 1: asb.v1.Delivery
	(*BrowserFillField)(nil),             // 2: asb.v1.BrowserFillField
	(*CreateSessionRequest)(nil),         // 3: asb.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),        // 4: asb.v1.CreateSessionResponse
	(*RequestGrantRequest)(nil),          // 5: asb.v1.RequestGrantRequest
	(*RequestGrantResponse)(nil),         // 6: asb.v1.RequestGrantResponse
	(*ApproveGrantRequest)(nil),          // 7: asb.v1.ApproveGrantRequest
	(*ApproveGrantResponse)(nil),         // 8: asb.v1.ApproveGrantResponse
	(*DenyGrantRequest)(nil),             // 9: asb.v1.DenyGrantRequest
	(*DenyGrantResponse)(nil),            // 10: asb.v1.DenyGrantResponse
	(*RevokeGrantRequest)(nil),           // 11: asb.v1.RevokeGrantRequest
	(*RevokeGrantResponse)(nil),          // 12: asb.v1.RevokeGrantResponse
	(*RevokeSessionRequest)(nil),         // 13: asb.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),        // 14: asb.v1.RevokeSessionResponse
	(*ExecuteGitHubProxyRequest)(nil),    // 15: asb.v1.ExecuteGitHubProxyRequest
	(*ExecuteGitHubProxyResponse)(nil),   // 16: asb.v1.ExecuteGitHubProxyResponse
	(*RegisterBrowserRelayRequest)(nil),  // 17: asb.v1.RegisterBrowserRelayRequest
	(*RegisterBrowserRelayResponse)(nil), // 18: asb.v1.RegisterBrowserRelayResponse
	(*UnwrapArtifactRequest)(nil),        // 19: asb.v1.UnwrapArtifactRequest
	(*UnwrapArtifactResponse)(nil),       // 20: asb.v1.UnwrapArtifactResponse
	nil,                                  // 21: asb.v1.RegisterBrowserRelayRequest.SelectorsEntry
	(*timestamppb.Timestamp)(nil),        // 22: google.protobuf.Timestamp
	(*structpb.Struct)(nil),              // 23: google.protobuf.Struct
}
var file_asb_v1_broker_proto_depIdxs = []int32{
	0,  // 0: asb.v1.CreateSessionRequest.attestation:type_name -> asb.v1.Attestation
	22, // 1: asb.v1.CreateSessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 2: asb.v1.RequestGrantResponse.delivery:type_name -> asb.v1.Delivery
	22, // 3: asb.v1.RequestGrantResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 4: asb.v1.ApproveGrantResponse.delivery:type_name -> asb.v1.Delivery
	22, // 5: asb.v1.ApproveGrantResponse.expires_at:type_name -> google.protobuf.Timestamp
	23, // 6: asb.v1.ExecuteGitHubProxyRequest.params:type_name -> google.protobuf.Struct
	21, // 7: asb.v1.RegisterBrowserRelayRequest.selectors:type_name -> asb.v1.RegisterBrowserRelayRequest.SelectorsEntry
	22, // 8: asb.v1.RegisterBrowserRelayResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 9: asb.v1.UnwrapArtifactResponse.fields:type_name -> asb.v1.BrowserFillField
	3,  // 10: asb.v1.BrokerService.CreateSession:input_type -> asb.v1.CreateSessionRequest
	5,  // 11: asb.v1.BrokerService.RequestGrant:input_type -> asb.v1.RequestGrantRequest
	7,  // 12: asb.v1.BrokerService.ApproveGrant:input_type -> asb.v1.ApproveGrantRequest
	9,  // 13: asb.v1.BrokerService.DenyGrant:input_type -> asb.v1.DenyGrantRequest
	11, // 14: asb.v1.BrokerService.RevokeGrant:input_type -> asb.v1.RevokeGrantRequest
	13, // 15: asb.v1.BrokerService.RevokeSession:input_type -> asb.v1.RevokeSessionRequest
	15, // 16: asb.v1.BrokerService.ExecuteGitHubProxy:input_type -> asb.v1.ExecuteGitHubProxyRequest
	17, // 17: asb.v1.BrokerService.RegisterBrowserRelay:input_type -> asb.v1.RegisterBrowserRelayRequest
	19, // 18: asb.v1.BrokerService.UnwrapArtifact:input_type -> asb.v1.UnwrapArtifactRequest
	4,  // 19: asb.v1.BrokerService.CreateSession:output_type -> asb.v1.CreateSessionResponse
	6,  // 20: asb.v1.BrokerService.RequestGrant:output_type -> asb.v1.RequestGrantResponse
	8,  // 21: asb.v1.BrokerService.ApproveGrant:output_type -> asb.v1.ApproveGrantResponse
	10, // 22: asb.v1.BrokerService.DenyGrant:output_type -> asb.v1.DenyGrantResponse
	12, // 23: asb.v1.BrokerService.RevokeGrant:output_type -> asb.v1.RevokeGrantResponse
	14, // 24: asb.v1.BrokerService.RevokeSession:output_type -> asb.v1.RevokeSessionResponse
	16, // 25: asb.v1.BrokerService.ExecuteGitHubProxy:output_type -> asb.v1.ExecuteGitHubProxyResponse
	18, // 26: asb.v1.BrokerService.RegisterBrowserRelay:output_type -> asb.v1.RegisterBrowserRelayResponse
	20, // 27: asb.v1.BrokerService.UnwrapArtifact:output_type -> asb.v1.UnwrapArtifactResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_asb_v1_broker_proto_init() }
func file_asb_v1_broker_proto_init() {
	if File_asb_v1_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asb_v1_broker_proto_rawDesc), len(file_asb_v1_broker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asb_v1_broker_proto_goTypes,
		DependencyIndexes: file_asb_v1_broker_proto_depIdxs,
		MessageInfos:      file_asb_v1_broker_proto_msgTypes,
	}.Build()
	File_asb_v1_broker_proto = out.File
	file_asb_v1_broker_proto_goTypes = nil
	file_asb_v1_broker_proto_depIdxs = nil
}
